name: Format Markdown

on:
  push:
    branches:
      - main
    paths:
      - '**.md'

jobs:
  format-markdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Install Prettier
      run: npm install --save-dev prettier

    - name: Format Markdown files
      run: npx prettier --write "**/*.md" --prose-wrap always

    - name: Commit and push changes
      if: github.event_name == 'push'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add "**/*.md"
        git commit -m "style: auto-format Markdown files" || echo "No changes to commit"
        git push
        